language: php

php:
  - 5.6
  - 5.5
  - 5.4

env:
- DB=mysql
- DB=pgsql

install: true

before_script:
  - touch .env
  - if [[ "$DB" == "mysql" ]]; then mysql -e 'create database transi;'; fi
  - if [[ "$DB" == "pgsql" ]]; then psql -c 'create database transi' -U postgres; fi
  - printf "APP_ENV=travis-${DB}\n" > .env;
  - make travis

script:
  - make check
