language: php

php:
  - 5.6
  - 5.5
  - 5.4

env:
- DB=mysql
- DB=postgresql

install: true

before_script:
  - touch .env
  - if [[ "$DB" == "mysql" ]]; then mysql -e 'create database transi;'; printf "DB_USER=travis\n" >> .env; fi
  - if [[ "$DB" == "postgresql" ]]; then psql -c 'create database transi' -U postgres; printf "DB_USER=postgres\n" >> .env; fi
  - make travis

script:
  - make check
